var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var TimeStampPlugin = require('timestamp-webpack-plugin');

// var commonsPlugin = new webpack.optimize.CommonsChunkPlugin('shared.js');

module.exports = {
  context: path.resolve('app'),
  // context: path.resolve('js'),
  entry: [
    './app'
  ],
  // entry: {
  //   about: './components/AboutPage.jsx',
  //   contact: './components/ContactPage.jsx',
  //   home: './components/HomePage.jsx'
  // },

  // [
    // './app.js',
    // './utils.js'
    // './app',
    // './utils/'
  // ],

  output: {
    path: path.resolve(__dirname, 'build/'),
    publicPath: 'public/assets/',
    filename: 'bundle.js'
    // filename: "[name].js"
  },

  plugins: [
    new ExtractTextPlugin('style.css'),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    }),
    new TimeStampPlugin({
      path: __dirname,
      file: 'timestamp.json'
    }),
    new webpack.BannerPlugin('********************************* *\nGenerated by ViCTHoR with webpack *\n********************************* *\n')
  ],
  // plugins : [commonsPlugin],

  devServer: {
    contentBase: 'public/'
  },

  module: {
    preLoaders: [
      {
        test: /\.js$|\.es6$/,
        exclude: /'node_modules'/,
        loader: 'jshint-loader'
      }
    ],
    loaders: [
      {
        test: /\.jsx?$|\.es6$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      }, {
        test: /\.css$/,
        exclude: /node_modules/,
        // loaders: ['style', 'css']
        // loader: ExtractTextPlugin.extract('style', 'css!autoprefixer')
        loader: ExtractTextPlugin.extract('style', 'css-loader')
      }, {
        test: /\.scss$/,
        exclude: /node_modules/,
        // loaders: ['style', 'css', 'sass']
        loader: ExtractTextPlugin.extract('style', 'css!autoprefixer!sass', {publicPath: './'})
      }, {
        test: /\.less$/,
        exclude: /node_modules/,
        // loaders: ['style', 'css', 'less']
        loader: ExtractTextPlugin.extract(['style', 'css!autoprefixer!less'])
      }, {
        test: /\.(png|jpe&g|ttf|eot)$/,
        exclude: /node_modules/,
        loader: 'url?limit=10000&name=[path][name].[ext]'
      }, {
        test: /\.json$/,
        exclude: /node_modules/,
        loader: 'json!' + path.resolve('./app/loaders/strip')
      }
    ]
  },

  resolve: {
    extensions: ['', '.js', '.jsx', '.es6']
  }
}
